"""Generation of typed Python package APIs from compiled Spork modules."""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Optional, overload

from spork.runtime.types import normalize_name
from spork.project.config import ProjectConfig, PythonAPIConfig, SporkAPIConfig

GENERATED_API_HEADER = "# Generated by spork build from :api; do not edit."
GENERATED_SPORK_API_HEADER = ";; Generated by spork build from :api; do not edit."
GENERATED_STUB_HEADER = "# Generated by spork build from typed Spork declarations; do not edit."


def normalize_module_name(name: str) -> str:
    """Normalize each Lisp-style namespace segment to a Python identifier."""
    parts = name.split(".")
    normalized = [normalize_name(part) for part in parts]
    if not normalized or any(not part.isidentifier() for part in normalized):
        raise ValueError(f"Invalid module or namespace name in :api: {name!r}")
    return ".".join(normalized)


@overload
def _stub_arg(argument: None) -> None: ...


@overload
def _stub_arg(argument: ast.arg) -> ast.arg: ...


def _stub_arg(argument: Optional[ast.arg]) -> Optional[ast.arg]:
    if argument is None:
        return None
    annotation = argument.annotation
    if annotation is None and argument.arg not in {"self", "cls"}:
        annotation = ast.Name(id="Any", ctx=ast.Load())
    return ast.arg(arg=argument.arg, annotation=annotation)


def _stub_arguments(arguments: ast.arguments) -> ast.arguments:
    return ast.arguments(
        posonlyargs=[_stub_arg(argument) for argument in arguments.posonlyargs],
        args=[_stub_arg(argument) for argument in arguments.args],
        vararg=_stub_arg(arguments.vararg),
        kwonlyargs=[_stub_arg(argument) for argument in arguments.kwonlyargs],
        kw_defaults=[
            ast.Constant(value=Ellipsis) if value is not None else None
            for value in arguments.kw_defaults
        ],
        kwarg=_stub_arg(arguments.kwarg),
        defaults=[ast.Constant(value=Ellipsis) for _ in arguments.defaults],
    )


def _stub_function(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> ast.FunctionDef | ast.AsyncFunctionDef:
    returns = node.returns
    if node.name == "__init__" and returns is None:
        returns = ast.Constant(value=None)
    elif returns is None:
        returns = ast.Name(id="Any", ctx=ast.Load())
    function_type = (
        ast.AsyncFunctionDef
        if isinstance(node, ast.AsyncFunctionDef)
        else ast.FunctionDef
    )
    return function_type(
        name=node.name,
        args=_stub_arguments(node.args),
        body=[ast.Expr(value=ast.Constant(value=Ellipsis))],
        decorator_list=node.decorator_list,
        returns=returns,
        type_comment=None,
    )


def _is_public_method(name: str) -> bool:
    return not name.startswith("_") or (name.startswith("__") and name.endswith("__"))


def _infer_constant_annotation(value: object) -> ast.expr:
    if isinstance(value, bool):
        name = "bool"
    elif isinstance(value, int):
        name = "int"
    elif isinstance(value, float):
        name = "float"
    elif isinstance(value, str):
        name = "str"
    elif isinstance(value, bytes):
        name = "bytes"
    else:
        name = "Any"
    return ast.Name(id=name, ctx=ast.Load())


def _assignment_name(node: ast.Assign) -> Optional[str]:
    if len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
        return node.targets[0].id
    return None


def _is_typing_factory(value: ast.expr) -> bool:
    if not isinstance(value, ast.Call):
        return False
    function = value.func
    if isinstance(function, ast.Name):
        name = function.id
    elif isinstance(function, ast.Attribute):
        name = function.attr
    else:
        return False
    return name in {"TypeVar", "ParamSpec", "TypeVarTuple", "NewType"}


def _stub_assignment(node: ast.Assign) -> Optional[ast.stmt]:
    name = _assignment_name(node)
    if not name or name.startswith("_"):
        return None
    if _is_typing_factory(node.value):
        return node
    annotation = (
        _infer_constant_annotation(node.value.value)
        if isinstance(node.value, ast.Constant)
        else ast.Name(id="Any", ctx=ast.Load())
    )
    return ast.AnnAssign(
        target=ast.Name(id=name, ctx=ast.Store()),
        annotation=annotation,
        value=None,
        simple=1,
    )


def _stub_class(node: ast.ClassDef) -> ast.ClassDef:
    body: list[ast.stmt] = []
    for item in node.body:
        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if _is_public_method(item.name):
                body.append(_stub_function(item))
        elif isinstance(item, ast.AnnAssign):
            if isinstance(item.target, ast.Name) and not item.target.id.startswith("_"):
                body.append(
                    ast.AnnAssign(
                        target=item.target,
                        annotation=item.annotation,
                        value=None,
                        simple=item.simple,
                    )
                )
        elif isinstance(item, ast.Assign):
            assignment = _stub_assignment(item)
            if assignment is not None:
                body.append(assignment)
        elif isinstance(item, ast.ClassDef) and not item.name.startswith("_"):
            body.append(_stub_class(item))
    if not body:
        body.append(ast.Expr(value=ast.Constant(value=Ellipsis)))
    return ast.ClassDef(
        name=node.name,
        bases=node.bases,
        keywords=node.keywords,
        body=body,
        decorator_list=node.decorator_list,
    )


def _is_runtime_bootstrap_import(node: ast.ImportFrom) -> bool:
    return node.module == "spork.runtime" and all(
        alias.name == "setup_runtime_env" for alias in node.names
    )


def module_stub_ast(module: ast.Module) -> ast.Module:
    """Reduce an importable generated module to its public declarations."""
    body: list[ast.stmt] = [
        ast.ImportFrom(
            module="__future__",
            names=[ast.alias(name="annotations")],
            level=0,
        ),
        ast.ImportFrom(
            module="typing",
            names=[ast.alias(name="Any", asname="Any")],
            level=0,
        ),
    ]
    for node in module.body:
        if isinstance(node, ast.ImportFrom):
            if not _is_runtime_bootstrap_import(node) and node.module != "__future__":
                body.append(
                    ast.ImportFrom(
                        module=node.module,
                        names=[
                            ast.alias(
                                name=alias.name,
                                asname=alias.asname or alias.name,
                            )
                            for alias in node.names
                        ],
                        level=node.level,
                    )
                )
        elif isinstance(node, ast.Import):
            body.append(
                ast.Import(
                    names=[
                        ast.alias(
                            name=alias.name,
                            asname=alias.asname or alias.name.split(".")[0],
                        )
                        for alias in node.names
                    ]
                )
            )
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                body.append(_stub_function(node))
        elif isinstance(node, ast.ClassDef):
            if not node.name.startswith("_"):
                body.append(_stub_class(node))
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name) and not node.target.id.startswith("_"):
                body.append(
                    ast.AnnAssign(
                        target=node.target,
                        annotation=node.annotation,
                        value=None,
                        simple=node.simple,
                    )
                )
        elif isinstance(node, ast.Assign):
            name = _assignment_name(node)
            if name == "__all__":
                continue
            assignment = _stub_assignment(node)
            if assignment is not None:
                body.append(assignment)
    return ast.Module(body=body, type_ignores=[])


def _write_generated(path: Path, content: str, header: str) -> None:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing and not existing.startswith(header):
            raise ValueError(
                f"Generated Python API would overwrite hand-written file: {path}"
            )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate_module_stub(python_path: Path) -> Path:
    """Generate a ``.pyi`` from annotations in one compiled Spork module."""
    module = ast.parse(python_path.read_text(encoding="utf-8"))
    stub = module_stub_ast(module)
    ast.fix_missing_locations(stub)
    content = GENERATED_STUB_HEADER + "\n" + ast.unparse(stub) + "\n"
    stub_path = python_path.with_suffix(".pyi")
    _write_generated(stub_path, content, GENERATED_STUB_HEADER)
    return stub_path


def _api_exports(api: PythonAPIConfig) -> list[tuple[str, str]]:
    exports = [(normalize_name(name), normalize_name(name)) for name in api.exports]
    exports.extend(
        (normalize_name(source), normalize_name(public))
        for source, public in api.aliases.items()
    )
    public_names = [public for _, public in exports]
    duplicates = sorted({name for name in public_names if public_names.count(name) > 1})
    if duplicates:
        raise ValueError(
            ":api :python exports duplicate public names: " + ", ".join(duplicates)
        )
    if any(
        not source.isidentifier() or not public.isidentifier()
        for source, public in exports
    ):
        raise ValueError(
            ":api :python exports and aliases must normalize to Python identifiers"
        )
    return exports


def _import_module_for_package(
    package_name: str, source_module: str
) -> tuple[str, str]:
    package = normalize_module_name(package_name)
    prefix = package + "."
    if source_module.startswith(prefix):
        import_module = "." + source_module[len(prefix) :]
    elif source_module == package:
        raise ValueError(":api :from cannot be the generated package initializer")
    else:
        import_module = source_module
    return package, import_module


def _import_module(
    api: PythonAPIConfig, source_module: str
) -> tuple[str, str]:
    return _import_module_for_package(api.package, source_module)


def _render_import(import_module: str, exports: list[tuple[str, str]]) -> str:
    lines = [f"from {import_module} import ("]
    lines.extend(f"    {source} as {public}," for source, public in exports)
    lines.append(")")
    return "\n".join(lines)


def _available_names(source_path: Path) -> set[str]:
    available: set[str] = set()
    source_ast = ast.parse(source_path.read_text(encoding="utf-8"))
    for node in source_ast.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            available.add(node.name)
        elif isinstance(node, ast.ImportFrom):
            available.update(
                alias.asname or alias.name
                for alias in node.names
                if alias.name != "*"
            )
        elif isinstance(node, ast.Import):
            available.update(
                alias.asname or alias.name.split(".")[0] for alias in node.names
            )
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            if isinstance(node, ast.Assign):
                name = _assignment_name(node)
            else:
                name = node.target.id if isinstance(node.target, ast.Name) else None
            if name:
                available.add(name)
    return available


def _require_available(
    exports: list[str], available: set[str], target: str
) -> None:
    missing = sorted(set(exports).difference(available))
    if missing:
        raise ValueError(
            f":api :{target} exports are missing from the source module: "
            + ", ".join(missing)
        )


def _generate_spork_api(
    out_dir: Path,
    api: SporkAPIConfig,
    source_namespace: str,
    available: set[str],
) -> Path:
    namespace = normalize_module_name(api.namespace)
    normalized_source = normalize_module_name(source_namespace)
    if namespace == normalized_source:
        raise ValueError(":api :spork :namespace cannot equal :api :from")

    normalized_exports = [normalize_name(name) for name in api.exports]
    if any(not name.isidentifier() for name in normalized_exports):
        raise ValueError(":api :spork exports must normalize to identifiers")
    duplicates = sorted(
        {name for name in normalized_exports if normalized_exports.count(name) > 1}
    )
    if duplicates:
        raise ValueError(
            ":api :spork exports duplicate normalized names: "
            + ", ".join(duplicates)
        )
    _require_available(normalized_exports, available, "spork")

    export_text = " ".join(api.exports)
    content = (
        f"{GENERATED_SPORK_API_HEADER}\n"
        f"(ns {api.namespace}\n"
        f"  (:require [{source_namespace} :refer [{export_text}]]))\n"
    )
    init_path = out_dir / Path(*namespace.split(".")) / "__init__.spork"
    _write_generated(
        init_path,
        content,
        GENERATED_SPORK_API_HEADER,
    )
    return init_path


def _generate_python_api(
    out_dir: Path,
    config: ProjectConfig,
    api: PythonAPIConfig,
    source_module: str,
    available: set[str],
    compiled_python: list[Path],
    runtime_exports: list[tuple[str, str]],
) -> list[Path]:
    package, import_module = _import_module(api, source_module)
    exports = _api_exports(api)
    _require_available([source for source, _ in exports], available, "python")

    generated: list[Path] = []
    package_dir = out_dir / Path(*package.split("."))
    import_exports = list(exports)
    public_targets = {public for _, public in exports}
    import_exports.extend(
        export for export in runtime_exports if export[1] not in public_targets
    )
    import_block = _render_import(import_module, import_exports)
    public_import_block = _render_import(import_module, exports)
    public_names = [public for _, public in exports]
    if api.include_version:
        public_names.append("__version__")

    init_lines = [
        GENERATED_API_HEADER,
        '"""Generated Python API for this Spork package."""',
        "",
        import_block,
    ]
    if api.include_version:
        init_lines.extend(["", f"__version__ = {config.version!r}"])
    init_lines.extend(["", f"__all__ = {public_names!r}", ""])
    init_path = package_dir / "__init__.py"
    _write_generated(init_path, "\n".join(init_lines), GENERATED_API_HEADER)
    generated.append(init_path)

    if api.typed:
        for python_path in compiled_python:
            generated.append(generate_module_stub(python_path))

        stub_lines = [GENERATED_API_HEADER, public_import_block]
        if api.include_version:
            stub_lines.extend(["", "__version__: str"])
        stub_lines.extend(["", "__all__: list[str]", ""])
        init_stub_path = package_dir / "__init__.pyi"
        _write_generated(
            init_stub_path,
            "\n".join(stub_lines),
            GENERATED_API_HEADER,
        )
        generated.append(init_stub_path)

        marker = package_dir / "py.typed"
        marker.parent.mkdir(parents=True, exist_ok=True)
        if marker.exists() and marker.read_text(encoding="utf-8"):
            raise ValueError(
                f"Generated Python API would overwrite hand-written file: {marker}"
            )
        marker.write_text("", encoding="utf-8")
        generated.append(marker)

    return generated


def _generate_spork_python_bridge(
    out_dir: Path,
    package_name: str,
    source_module: str,
    runtime_exports: list[tuple[str, str]],
) -> Path:
    """Generate the runtime package imported by AOT-compiled Spork code."""
    package, import_module = _import_module_for_package(
        package_name,
        source_module,
    )
    import_block = _render_import(import_module, runtime_exports)
    content = "\n".join(
        [
            GENERATED_API_HEADER,
            '"""Generated runtime bridge for the public Spork namespace."""',
            "",
            import_block,
            "",
            "__all__: list[str] = []",
            "",
        ]
    )
    init_path = out_dir / Path(*package.split(".")) / "__init__.py"
    _write_generated(init_path, content, GENERATED_API_HEADER)
    return init_path


def generate_public_api(
    out_dir: Path,
    config: ProjectConfig,
    compiled_python: list[Path],
) -> list[Path]:
    """Generate the configured Spork namespace and Python package APIs."""
    api = config.api
    if api is None:
        return []

    source_module = normalize_module_name(api.source_module)
    source_path = out_dir / Path(*source_module.split(".")).with_suffix(".py")
    if not source_path.is_file():
        raise ValueError(f":api :from module was not compiled: {api.source_module!r}")
    available = _available_names(source_path)

    generated: list[Path] = []
    runtime_exports: list[tuple[str, str]] = []
    spork_package = None
    if api.spork is not None:
        generated.append(
            _generate_spork_api(
                out_dir,
                api.spork,
                api.source_module,
                available,
            )
        )
        spork_package = normalize_module_name(api.spork.namespace)
        runtime_exports = [
            (normalize_name(name), normalize_name(name))
            for name in api.spork.exports
        ]

    python_package = (
        normalize_module_name(api.python.package)
        if api.python is not None
        else None
    )
    if spork_package is not None and spork_package != python_package:
        generated.append(
            _generate_spork_python_bridge(
                out_dir,
                spork_package,
                source_module,
                runtime_exports,
            )
        )

    if api.python is not None:
        generated.extend(
            _generate_python_api(
                out_dir,
                config,
                api.python,
                source_module,
                available,
                compiled_python,
                runtime_exports if spork_package == python_package else [],
            )
        )
    return generated
