"""Lowering for definitions, parameters, and function expressions."""

import ast
from typing import Optional, cast

from spork.compiler.annotations import (
    compile_type_annotation,
    extract_decorators_and_type,
)
from spork.compiler.arity import (
    has_pattern_dispatch,
    is_multi_arity,
    parse_arity,
    parse_arity_with_patterns,
)
from spork.compiler.ast_helpers import contains_yield, flatten_stmts
from spork.compiler.context import get_compile_context
from spork.compiler.control_flow import (
    compile_do_stmt_with_return,
    compile_let_stmt_with_return,
    compile_with_stmt_with_return,
)
from spork.compiler.destructuring import (
    compile_destructure,
    is_destructuring_pattern,
)
from spork.compiler.exceptions import compile_try_stmt_with_return
from spork.compiler.generated_names import gen_fn_name, gensym
from spork.compiler.loops import compile_loop_stmt_with_return
from spork.compiler.lowering import compile_expr, compile_stmt
from spork.compiler.macros import is_symbol
from spork.compiler.patterns import compile_pattern_check
from spork.compiler.reader import copy_location, get_source_location, set_location
from spork.runtime import Decorated, Symbol, VectorLiteral
from spork.runtime.types import normalize_name


def _get_specialized_vector_constructor(type_expr, value_form):
    """
    Check if we can optimize to a specialized vector constructor.

    Returns 'vec_f64', 'vec_i64', or None.

    Only optimizes when:
    1. Type annotation is (Vector float) or (Vector int)
    2. Value is a vector literal [...]
    """
    # Only optimize vector literals
    if not isinstance(value_form, VectorLiteral):
        return None

    # Check if type_expr is (Vector float) or (Vector int)
    if not isinstance(type_expr, list) or len(type_expr) != 2:
        return None

    base, elem_type = type_expr
    if not (isinstance(base, Symbol) and base.name == "Vector"):
        return None

    if isinstance(elem_type, Symbol):
        if elem_type.name == "float":
            return "vec_f64"
        elif elem_type.name == "int":
            return "vec_i64"

    return None


def _make_specialized_vector_call(constructor, vector_literal):
    """
    Convert a vector literal to a specialized constructor call.

    [1.0 2.0 3.0] with constructor='vec_f64'
    → vec_f64(1.0, 2.0, 3.0)
    """
    # Compile each element
    args = [compile_expr(elem) for elem in vector_literal.items]

    # Build: vec_f64(args...) or vec_i64(args...)
    # These are available directly in the runtime environment
    func = ast.Name(id=constructor, ctx=ast.Load())

    return ast.Call(func=func, args=args, keywords=[])


def compile_def(args, form_loc=None):
    """
    Compile (def name value) or (def pattern value) for destructuring.

    Supports:
    - Simple: (def x 42)
    - With type annotation: (def ^int x 42) -> x: int = 42
    - Generic types: (def ^(List int) items []) -> items: List[int] = []
    - Specialized vectors: (def ^(Vector float) data [1.0 2.0]) -> uses vec_f64
    - Vector destructuring: (def [a b] [1 2])
    - Dict destructuring: (def {:keys [x y]} {:x 1 :y 2})
    """
    if len(args) < 2:
        raise SyntaxError("def requires at least 2 arguments: name/pattern and value")

    # Check for type annotation: (def ^type name value)
    type_annotation = None
    type_expr_raw = None  # Keep the raw type expression for specialized vector check
    if isinstance(args[0], Decorated):
        if len(args) != 3:
            raise SyntaxError(
                "def with type annotation requires 3 arguments: ^type name value"
            )
        type_expr_raw = args[0].expr
        type_annotation = compile_type_annotation(type_expr_raw)
        pattern = args[1]
        value_form = args[2]
    else:
        if len(args) != 2:
            raise SyntaxError(
                "def requires exactly 2 arguments: name/pattern and value"
            )
        pattern = args[0]
        value_form = args[1]

    # Check for specialized vector optimization
    # If we have ^(Vector float) or ^(Vector int) with a vector literal,
    # use the specialized constructor for better performance
    specialized_constructor = None
    if type_expr_raw is not None:
        specialized_constructor = _get_specialized_vector_constructor(
            type_expr_raw, value_form
        )

    # Capture only anonymous functions generated by this value expression.
    # Clearing the entire context here can steal functions from an earlier
    # expression statement and place their definitions after their first use.
    ctx = get_compile_context()
    nested_start = len(ctx.nested_functions)
    if specialized_constructor:
        value = _make_specialized_vector_call(specialized_constructor, value_form)
    else:
        value = compile_expr(value_form)
    nested_funcs = ctx.nested_functions[nested_start:]
    ctx.nested_functions = ctx.nested_functions[:nested_start]

    # If we have a type annotation and a simple symbol, emit AnnAssign
    if type_annotation is not None and isinstance(pattern, Symbol):
        var_name = normalize_name(pattern.name)
        stmt = ast.AnnAssign(
            target=ast.Name(id=var_name, ctx=ast.Store()),
            annotation=type_annotation,
            value=value,
            simple=1,  # Required for module-level annotations
        )
        if form_loc:
            set_location(stmt, form_loc)
        else:
            copy_location(stmt, pattern)

        if nested_funcs:
            return nested_funcs + [stmt]
        return stmt

    # Use compile_destructure for all patterns (handles both simple symbols and complex patterns)
    stmts = compile_destructure(pattern, value, form_loc)

    if nested_funcs:
        # Return a list with function defs followed by the destructuring assignments
        return nested_funcs + stmts

    # If single statement, return it directly; otherwise return list
    if len(stmts) == 1:
        return stmts[0]
    return stmts


def compile_defmacro(args):
    """
    (defmacro name [params] body...)
    This should not be called during normal compilation since defmacros
    are processed in a first pass. Returns a pass statement.
    """
    # Return a pass statement (macros don't generate runtime code)
    return ast.Pass()


def compile_defclass(args, form_loc=None):
    """
    Compile class definitions.

    Syntax:
        (defclass Name body...)
        (defclass Name [Parent1 Parent2] body...)
        (defclass ^decorator Name body...)
        (defclass ^decorator1 ^decorator2 Name [Parent] body...)

    Body can contain:
        - (defn method-name [self ...] ...) for methods
        - (def class-var value) for class variables
        - (field name type) for annotated fields (no default)
        - (field name type default) for annotated fields with default
        - (defn ^staticmethod name [...] ...) for static methods
        - (defn ^classmethod name [cls ...] ...) for class methods
        - (defn ^property name [self] ...) for properties

    Examples:
        (defclass Point
          (defn __init__ [self x y]
            (set! self.x x)
            (set! self.y y))
          (defn __repr__ [self]
            (+ "Point(" (str self.x) ", " (str self.y) ")")))

        (defclass Child [Parent]
          (defn __init__ [self name]
            (call (super) __init__)
            (set! self.name name)))

        (defclass ^dataclass Config
          (field name str "default")
          (field debug bool false)
          (field max-retries int 3))
    """
    if len(args) < 1:
        raise SyntaxError("defclass requires at least a class name")

    # Collect decorators (^decorator before the name)
    decorators = []
    i = 0
    while i < len(args) and isinstance(args[i], Decorated):
        decorators.append(args[i].expr)
        i += 1
    args = args[i:]

    if len(args) < 1:
        raise SyntaxError("defclass requires a class name")

    name_sym = args[0]
    if not isinstance(name_sym, Symbol):
        raise SyntaxError("defclass name must be a symbol")

    class_name = normalize_name(name_sym.name)

    # Check for base classes: (defclass Name [Base1 Base2] body...)
    bases = []
    body_start = 1
    if len(args) > 1 and isinstance(args[1], VectorLiteral):
        for base in args[1].items:
            if (
                isinstance(base, list)
                and base
                and isinstance(base[0], Symbol)
                and base[0].name.rsplit(".", 1)[-1] == "Generic"
            ):
                bases.append(compile_type_annotation(base))
            else:
                bases.append(compile_expr(base))
        body_start = 2

    body_forms = args[body_start:]

    # Compile class body
    class_body = []
    for form in body_forms:
        if isinstance(form, list) and form:
            head = form[0]
            if is_symbol(head, "defn"):
                # Method definition
                method = compile_defn(form[1:])
                class_body.append(method)
            elif is_symbol(head, "def"):
                # Class variable
                var_stmts = compile_def(form[1:])
                if isinstance(var_stmts, list):
                    class_body.extend(var_stmts)
                else:
                    class_body.append(var_stmts)
            elif is_symbol(head, "field"):
                # Annotated field: (field name type) or (field name type default)
                field_stmts = compile_field(form[1:])
                class_body.extend(field_stmts)
            else:
                # Other statements (rare but possible)
                stmt = compile_stmt(form)
                if isinstance(stmt, list):
                    class_body.extend(stmt)
                else:
                    class_body.append(stmt)
        else:
            # Expression statement
            class_body.append(ast.Expr(value=compile_expr(form)))

    # Ensure class body is not empty
    if not class_body:
        class_body.append(ast.Pass())

    # Compile decorator expressions
    decorator_list = []
    for dec in decorators:
        if isinstance(dec, Symbol):
            # Simple decorator: ^dataclass -> @dataclass
            decorator_list.append(ast.Name(id=normalize_name(dec.name), ctx=ast.Load()))
        elif isinstance(dec, list) and dec:
            # Decorator with args: ^(decorator arg) -> @decorator(arg)
            decorator_list.append(compile_expr(dec))
        else:
            raise SyntaxError(f"Invalid decorator expression: {dec!r}")

    node = ast.ClassDef(
        name=class_name,
        bases=bases,
        keywords=[],
        body=class_body,
        decorator_list=decorator_list,
    )
    if form_loc:
        set_location(node, form_loc)
    else:
        copy_location(node, name_sym)
    return node


def compile_field(args):
    """
    Compile annotated field declarations for classes.

    Syntax:
        (field name type)         -> name: type
        (field name type default) -> name: type = default

    Examples:
        (field x int)             -> x: int
        (field name str "")       -> name: str = ""
        (field items list [])     -> items: list = []
    """
    if len(args) < 2:
        raise SyntaxError("field requires at least name and type")
    if len(args) > 3:
        raise SyntaxError("field takes at most name, type, and default")

    name_form = args[0]
    type_form = args[1]
    default_form = args[2] if len(args) == 3 else None

    if not isinstance(name_form, Symbol):
        raise SyntaxError("field name must be a symbol")

    field_name = normalize_name(name_form.name)
    type_expr = compile_expr(type_form)

    # Create annotated assignment: name: type or name: type = default
    target = ast.Name(id=field_name, ctx=ast.Store())

    if default_form is not None:
        # name: type = default
        default_expr = compile_expr(default_form)
        stmt = ast.AnnAssign(
            target=target,
            annotation=type_expr,
            value=default_expr,
            simple=1,
        )
    else:
        # name: type (no default)
        stmt = ast.AnnAssign(
            target=target,
            annotation=type_expr,
            value=None,
            simple=1,
        )

    return [stmt]


def compile_pattern_dispatch_clause(
    param_patterns, guard_expr, body_forms, ok_var, is_generator=False
):
    """
    Compile a single clause of pattern-based dispatch.

    Generates code that:
    1. Checks types and patterns for each parameter
    2. Binds variables (with type annotations when present)
    3. Checks guard if present
    4. Executes body if all checks pass

    Returns (stmts, bindings_made) where stmts is the list of statements
    and bindings_made indicates if any pattern matching was done.
    """
    stmts = []
    # bindings_list now contains (name, value_expr, type_expr) tuples
    # type_expr is None if no type annotation, otherwise the compiled type AST
    bindings_list = []
    # Track the current type annotation for the pattern being processed
    current_type_annotation = None
    arg_index = 0

    for param_info in param_patterns:
        if param_info[0] == "&":
            # Vararg: pattern, type_expr
            _, pattern, type_expr = param_info
            # Get rest of args
            value_expr = ast.Subscript(
                value=ast.Name(id="__args__", ctx=ast.Load()),
                slice=ast.Slice(
                    lower=ast.Constant(value=arg_index),
                    upper=None,
                    step=None,
                ),
                ctx=ast.Load(),
            )
            # Type check if present
            if type_expr is not None:
                type_ast = compile_expr(type_expr)
                check = ast.If(
                    test=ast.BoolOp(
                        op=ast.And(),
                        values=[
                            ast.Name(id=ok_var, ctx=ast.Load()),
                            ast.UnaryOp(
                                op=ast.Not(),
                                operand=ast.Call(
                                    func=ast.Name(id="isinstance", ctx=ast.Load()),
                                    args=[value_expr, type_ast],
                                    keywords=[],
                                ),
                            ),
                        ],
                    ),
                    body=[
                        ast.Assign(
                            targets=[ast.Name(id=ok_var, ctx=ast.Store())],
                            value=ast.Constant(value=False),
                        )
                    ],
                    orelse=[],
                )
                stmts.append(check)
                # Set current type annotation for bindings created by pattern check
                current_type_annotation = compile_type_annotation(type_expr)
            else:
                current_type_annotation = None
            # Pattern match - pass type annotation for bindings
            stmts.extend(
                compile_pattern_check(
                    pattern, value_expr, ok_var, bindings_list, current_type_annotation
                )
            )

        elif param_info[0] == "**":
            # Kwargs: pattern
            _, pattern, _ = param_info
            value_expr = ast.Name(id="__kwargs__", ctx=ast.Load())
            stmts.extend(
                compile_pattern_check(pattern, value_expr, ok_var, bindings_list)
            )

        else:
            # Regular parameter: (pattern, _, type_expr)
            pattern, _, type_expr = param_info
            value_expr = ast.Subscript(
                value=ast.Name(id="__args__", ctx=ast.Load()),
                slice=ast.Constant(value=arg_index),
                ctx=ast.Load(),
            )
            # Type check if present
            if type_expr is not None:
                type_ast = compile_expr(type_expr)
                check = ast.If(
                    test=ast.BoolOp(
                        op=ast.And(),
                        values=[
                            ast.Name(id=ok_var, ctx=ast.Load()),
                            ast.UnaryOp(
                                op=ast.Not(),
                                operand=ast.Call(
                                    func=ast.Name(id="isinstance", ctx=ast.Load()),
                                    args=[value_expr, type_ast],
                                    keywords=[],
                                ),
                            ),
                        ],
                    ),
                    body=[
                        ast.Assign(
                            targets=[ast.Name(id=ok_var, ctx=ast.Store())],
                            value=ast.Constant(value=False),
                        )
                    ],
                    orelse=[],
                )
                stmts.append(check)
                # Set current type annotation for bindings created by pattern check
                current_type_annotation = compile_type_annotation(type_expr)
            else:
                current_type_annotation = None
            # Pattern match - pass type annotation for bindings
            stmts.extend(
                compile_pattern_check(
                    pattern, value_expr, ok_var, bindings_list, current_type_annotation
                )
            )
            arg_index += 1

    # Build the body that runs when patterns match
    match_body = []

    # Add bindings - now with type annotations when present
    for binding in bindings_list:
        if len(binding) == 3:
            name, val_expr, type_annotation = binding
        else:
            # Backward compatibility
            name, val_expr = binding
            type_annotation = None

        if type_annotation is not None:
            # Emit annotated assignment: x: int = value
            match_body.append(
                ast.AnnAssign(
                    target=ast.Name(id=normalize_name(name), ctx=ast.Store()),
                    annotation=type_annotation,
                    value=val_expr,
                    simple=1,
                )
            )
        else:
            match_body.append(
                ast.Assign(
                    targets=[ast.Name(id=normalize_name(name), ctx=ast.Store())],
                    value=val_expr,
                )
            )

    # Save nested functions count before compiling body/guard
    ctx = get_compile_context()
    saved_funcs_count = len(ctx.nested_functions)

    # Compile guard if present
    if guard_expr is not None:
        guard_compiled = compile_expr(guard_expr)

        # Compile body forms
        body_stmts = []
        for f in body_forms[:-1]:
            s = compile_stmt(f)
            body_stmts.extend(flatten_stmts([s]))

        # Last form - return it
        last_form = body_forms[-1]
        if isinstance(last_form, list) and last_form and is_symbol(last_form[0]):
            head_name = last_form[0].name
            if head_name == "let":
                body_stmts.extend(
                    flatten_stmts([compile_let_stmt_with_return(last_form[1:])])
                )
            elif head_name == "do":
                body_stmts.extend(
                    flatten_stmts([compile_do_stmt_with_return(last_form[1:])])
                )
            elif head_name in ("while", "set!"):
                body_stmts.extend(flatten_stmts([compile_stmt(last_form)]))
                if not is_generator:
                    body_stmts.append(ast.Return(value=ast.Constant(value=None)))
            elif head_name == "return":
                body_stmts.extend(flatten_stmts([compile_stmt(last_form)]))
            else:
                if is_generator:
                    body_stmts.extend(flatten_stmts([compile_stmt(last_form)]))
                else:
                    body_stmts.append(ast.Return(value=compile_expr(last_form)))
        else:
            if is_generator:
                body_stmts.extend(flatten_stmts([compile_stmt(last_form)]))
            else:
                body_stmts.append(ast.Return(value=compile_expr(last_form)))

        # Extract nested functions
        nested_funcs = ctx.nested_functions[saved_funcs_count:]
        ctx.nested_functions = ctx.nested_functions[:saved_funcs_count]
        match_body.extend(nested_funcs)

        # Wrap body in guard check
        guard_if = ast.If(
            test=guard_compiled,
            body=body_stmts if body_stmts else [ast.Pass()],
            orelse=[],
        )
        match_body.append(guard_if)
    else:
        # No guard - compile body directly
        for f in body_forms[:-1]:
            s = compile_stmt(f)
            match_body.extend(flatten_stmts([s]))

        last_form = body_forms[-1]
        if isinstance(last_form, list) and last_form and is_symbol(last_form[0]):
            head_name = last_form[0].name
            if head_name == "let":
                match_body.extend(
                    flatten_stmts([compile_let_stmt_with_return(last_form[1:])])
                )
            elif head_name == "do":
                match_body.extend(
                    flatten_stmts([compile_do_stmt_with_return(last_form[1:])])
                )
            elif head_name in ("while", "set!"):
                match_body.extend(flatten_stmts([compile_stmt(last_form)]))
                if not is_generator:
                    match_body.append(ast.Return(value=ast.Constant(value=None)))
            elif head_name == "return":
                match_body.extend(flatten_stmts([compile_stmt(last_form)]))
            else:
                if is_generator:
                    match_body.extend(flatten_stmts([compile_stmt(last_form)]))
                else:
                    match_body.append(ast.Return(value=compile_expr(last_form)))
        else:
            if is_generator:
                match_body.extend(flatten_stmts([compile_stmt(last_form)]))
            else:
                match_body.append(ast.Return(value=compile_expr(last_form)))

        # Extract nested functions
        nested_funcs = ctx.nested_functions[saved_funcs_count:]
        ctx.nested_functions = ctx.nested_functions[:saved_funcs_count]
        # Insert nested funcs at beginning of match_body
        match_body = list(nested_funcs) + match_body

    # Wrap in: if ok_var: <match_body>
    if match_body:
        inner_if = ast.If(
            test=ast.Name(id=ok_var, ctx=ast.Load()),
            body=match_body,  # type: ignore
            orelse=[],
        )
        stmts.append(inner_if)

    return stmts


def compile_multi_arity_defn(
    name_sym,
    arity_forms,
    decorators=None,
    form_loc=None,
    is_async=False,
    is_generator=False,
    return_type_node=None,
):
    """
    Compile a multi-arity function definition with pattern matching support.

    Example:
        (defn add
          ([x] x)
          ([x y] (+ x y))
          ([x y & more] (+ x y (apply + more))))

    With pattern matching:
        (defn describe
          ([^int n :when (>= n 0)] "nonnegative int")
          ([^int n] "negative int")
          ([^str s] "string")
          ([x] "something else"))

    Generates:
        def add(*__args__, **__kwargs__):
            __n__ = len(__args__)
            if __n__ == 1:
                # Try each clause with arity 1 in order
                ...
            elif __n__ == 2:
                ...
            else:
                raise TypeError(...)
    """
    fn_name = normalize_name(name_sym.name)

    # Check if we need pattern dispatch
    use_pattern_dispatch = has_pattern_dispatch(arity_forms)

    if use_pattern_dispatch:
        return compile_multi_arity_pattern_defn(
            name_sym,
            arity_forms,
            decorators,
            form_loc,
            is_async,
            is_generator,
            return_type_node,
        )

    # Parse all arities (simple case without pattern matching)
    arities = []
    has_variadic = False
    has_any_kwargs = False

    for arity_form in arity_forms:
        params, body_forms, min_args, has_vararg, has_kwargs = parse_arity(arity_form)
        if has_vararg:
            if has_variadic:
                raise SyntaxError("Only one variadic arity allowed per function")
            has_variadic = True
        if has_kwargs:
            has_any_kwargs = True
        arities.append((params, body_forms, min_args, has_vararg, has_kwargs))

    # Sort arities: fixed arities first (by min_args), variadic last
    fixed_arities = [(p, b, m, v, k) for p, b, m, v, k in arities if not v]
    variadic_arities = [(p, b, m, v, k) for p, b, m, v, k in arities if v]

    # Check for duplicate fixed arities
    fixed_counts = [m for _, _, m, _, _ in fixed_arities]
    if len(fixed_counts) != len(set(fixed_counts)):
        raise SyntaxError("Duplicate arity definitions")

    # Sort fixed arities by arg count
    fixed_arities.sort(key=lambda x: x[2])

    # Build the dispatch function
    # def fn_name(*__args__, **__kwargs__):
    args_node = ast.arguments(
        posonlyargs=[],
        args=[],
        vararg=ast.arg(arg="__args__", annotation=None),
        kwonlyargs=[],
        kw_defaults=[],
        kwarg=ast.arg(arg="__kwargs__", annotation=None) if has_any_kwargs else None,
        defaults=[],
    )

    body_nodes = []

    # __n__ = len(__args__)
    body_nodes.append(
        ast.Assign(
            targets=[ast.Name(id="__n__", ctx=ast.Store())],
            value=ast.Call(
                func=ast.Name(id="len", ctx=ast.Load()),
                args=[ast.Name(id="__args__", ctx=ast.Load())],
                keywords=[],
            ),
        )
    )

    # Build if/elif chain for dispatch
    dispatch_cases = []

    for params, body_forms, min_args, _, has_kwargs in fixed_arities:
        # Condition: __n__ == min_args
        test = ast.Compare(
            left=ast.Name(id="__n__", ctx=ast.Load()),
            ops=[ast.Eq()],
            comparators=[ast.Constant(value=min_args)],
        )

        # Generate body for this arity
        arity_body = compile_arity_dispatch_body(
            params, body_forms, has_kwargs, is_generator
        )
        dispatch_cases.append((test, arity_body))

    # Add variadic arity if present
    if variadic_arities:
        params, body_forms, min_args, has_vararg, has_kwargs = variadic_arities[0]
        # Condition: __n__ >= min_args
        test = ast.Compare(
            left=ast.Name(id="__n__", ctx=ast.Load()),
            ops=[ast.GtE()],
            comparators=[ast.Constant(value=min_args)],
        )
        arity_body = compile_arity_dispatch_body(
            params, body_forms, has_kwargs, is_generator
        )
        dispatch_cases.append((test, arity_body))

    # Build the if/elif/else chain
    if dispatch_cases:
        # Start with the else clause (error)
        error_msg = f"{fn_name} called with wrong number of arguments"
        else_body = [
            ast.Raise(
                exc=ast.Call(
                    func=ast.Name(id="TypeError", ctx=ast.Load()),
                    args=[ast.Constant(value=error_msg)],
                    keywords=[],
                ),
                cause=None,
            )
        ]

        # Build from the end
        current_else: list[ast.stmt] = list(else_body)
        for test, arity_body in reversed(dispatch_cases):
            current_if = ast.If(
                test=test,
                body=arity_body,
                orelse=current_else,
            )
            current_else = [current_if]

        body_nodes.append(current_else[0])

    # Check for yield without ^generator annotation
    if contains_yield(body_nodes) and not is_generator:
        raise SyntaxError(
            f"Function '{fn_name}' contains yield but is not marked with ^generator. "
            f"Use (defn ^generator {name_sym.name} ...) for generator functions."
        )

    # Compile decorator expressions
    decorator_list = []
    if decorators:
        for dec in decorators:
            if isinstance(dec, Symbol):
                # Simple decorator: ^staticmethod -> @staticmethod
                decorator_list.append(
                    ast.Name(id=normalize_name(dec.name), ctx=ast.Load())
                )
            elif isinstance(dec, list) and dec:
                # Decorator with args: ^(route "/api") -> @route("/api")
                decorator_list.append(compile_expr(dec))
            else:
                raise SyntaxError(f"Invalid decorator expression: {dec!r}")

    if is_async:
        func = ast.AsyncFunctionDef(
            name=fn_name,
            args=args_node,
            body=body_nodes,
            decorator_list=decorator_list,
            returns=return_type_node,
        )
    else:
        func = ast.FunctionDef(
            name=fn_name,
            args=args_node,
            body=body_nodes,
            decorator_list=decorator_list,
            returns=return_type_node,
        )

    # Set source location on the function definition
    if form_loc:
        set_location(func, form_loc)
    else:
        copy_location(func, name_sym)

    # Inject any nested function definitions at the start of the function body
    nested_funcs = get_compile_context().get_and_clear_functions()
    if nested_funcs:
        func.body = nested_funcs + func.body

    return func


def compile_multi_arity_pattern_defn(
    name_sym,
    arity_forms,
    decorators=None,
    form_loc=None,
    is_async=False,
    is_generator=False,
    return_type_node=None,
):
    """
    Compile a multi-arity function definition with pattern matching dispatch.

    Groups clauses by arity, then tries each clause within an arity group
    in source order using pattern matching.

    Example:
        (defn describe
          ([^int n :when (>= n 0)] "nonnegative int")
          ([^int n] "negative int")
          ([^str s] "string")
          ([x] "something else"))
    """
    fn_name = normalize_name(name_sym.name)

    # Parse all arities with pattern info
    clauses = []
    has_any_kwargs = False

    for arity_form in arity_forms:
        param_patterns, guard_expr, body_forms, arity, has_vararg, has_kwargs = (
            parse_arity_with_patterns(arity_form)
        )
        if has_kwargs:
            has_any_kwargs = True
        clauses.append(
            (param_patterns, guard_expr, body_forms, arity, has_vararg, has_kwargs)
        )

    # Group clauses by arity
    # Variadic clauses (has_vararg=True) go in a separate group
    arity_groups = {}  # arity -> list of (param_patterns, guard_expr, body_forms, has_kwargs)
    variadic_clauses = []  # list of (param_patterns, guard_expr, body_forms, min_arity, has_kwargs)

    for (
        param_patterns,
        guard_expr,
        body_forms,
        arity,
        has_vararg,
        has_kwargs,
    ) in clauses:
        if has_vararg:
            # Count non-vararg params for min arity
            min_arity = sum(1 for p in param_patterns if p[0] not in ("&", "**"))
            variadic_clauses.append(
                (param_patterns, guard_expr, body_forms, min_arity, has_kwargs)
            )
        else:
            if arity not in arity_groups:
                arity_groups[arity] = []
            arity_groups[arity].append(
                (param_patterns, guard_expr, body_forms, has_kwargs)
            )

    # Build the dispatch function
    args_node = ast.arguments(
        posonlyargs=[],
        args=[],
        vararg=ast.arg(arg="__args__", annotation=None),
        kwonlyargs=[],
        kw_defaults=[],
        kwarg=ast.arg(arg="__kwargs__", annotation=None) if has_any_kwargs else None,
        defaults=[],
    )

    body_nodes = []

    # __n__ = len(__args__)
    body_nodes.append(
        ast.Assign(
            targets=[ast.Name(id="__n__", ctx=ast.Store())],
            value=ast.Call(
                func=ast.Name(id="len", ctx=ast.Load()),
                args=[ast.Name(id="__args__", ctx=ast.Load())],
                keywords=[],
            ),
        )
    )

    # Build if/elif chain for arity dispatch
    dispatch_cases = []

    # Sort arities for deterministic output
    for arity in sorted(arity_groups.keys()):
        group = arity_groups[arity]
        # Condition: __n__ == arity
        test = ast.Compare(
            left=ast.Name(id="__n__", ctx=ast.Load()),
            ops=[ast.Eq()],
            comparators=[ast.Constant(value=arity)],
        )

        # Generate body that tries each clause in order
        arity_body = compile_arity_pattern_group(group, fn_name, is_generator)
        dispatch_cases.append((test, arity_body))

    # Add variadic clauses
    # Sort by min_arity descending so more specific patterns are tried first
    variadic_clauses.sort(key=lambda x: x[3], reverse=True)
    for (
        param_patterns,
        guard_expr,
        body_forms,
        min_arity,
        has_kwargs,
    ) in variadic_clauses:
        test = ast.Compare(
            left=ast.Name(id="__n__", ctx=ast.Load()),
            ops=[ast.GtE()],
            comparators=[ast.Constant(value=min_arity)],
        )
        # Single clause for variadic
        arity_body = compile_arity_pattern_group(
            [(param_patterns, guard_expr, body_forms, has_kwargs)],
            fn_name,
            is_generator,
        )
        dispatch_cases.append((test, arity_body))

    # Build the if/elif/else chain
    if dispatch_cases:
        # Start with the else clause (error)
        error_msg = (
            f"{fn_name} called with wrong number of arguments or no matching pattern"
        )
        else_body = [
            ast.Raise(
                exc=ast.Call(
                    func=ast.Name(id="MatchError", ctx=ast.Load()),
                    args=[ast.Constant(value=error_msg)],
                    keywords=[],
                ),
                cause=None,
            )
        ]

        # Build from the end
        current_else: list[ast.stmt] = list(else_body)
        for test, arity_body in reversed(dispatch_cases):
            current_if = ast.If(
                test=test,
                body=arity_body,
                orelse=current_else,
            )
            current_else = [current_if]

        body_nodes.append(current_else[0])

    # Check for yield without ^generator annotation
    if contains_yield(body_nodes) and not is_generator:
        raise SyntaxError(
            f"Function '{fn_name}' contains yield but is not marked with ^generator. "
            f"Use (defn ^generator {name_sym.name} ...) for generator functions."
        )

    # Compile decorator expressions
    decorator_list = []
    if decorators:
        for dec in decorators:
            if isinstance(dec, Symbol):
                decorator_list.append(
                    ast.Name(id=normalize_name(dec.name), ctx=ast.Load())
                )
            elif isinstance(dec, list) and dec:
                decorator_list.append(compile_expr(dec))
            else:
                raise SyntaxError(f"Invalid decorator expression: {dec!r}")

    if is_async:
        func = ast.AsyncFunctionDef(
            name=fn_name,
            args=args_node,
            body=body_nodes,
            decorator_list=decorator_list,
            returns=return_type_node,
        )
    else:
        func = ast.FunctionDef(
            name=fn_name,
            args=args_node,
            body=body_nodes,
            decorator_list=decorator_list,
            returns=return_type_node,
        )

    if form_loc:
        set_location(func, form_loc)
    else:
        copy_location(func, name_sym)

    # Inject any nested function definitions at the start of the function body
    nested_funcs = get_compile_context().get_and_clear_functions()
    if nested_funcs:
        func.body = nested_funcs + func.body

    return func


def compile_arity_pattern_group(clauses, fn_name, is_generator=False):
    """
    Compile a group of clauses with the same arity.
    Tries each clause in order using pattern matching.
    Returns list of statements.
    """
    stmts = []

    for param_patterns, guard_expr, body_forms, _ in clauses:
        ok_var = gensym("__clause_ok_")

        # Initialize ok flag
        stmts.append(
            ast.Assign(
                targets=[ast.Name(id=ok_var, ctx=ast.Store())],
                value=ast.Constant(value=True),
            )
        )

        # Compile pattern matching for this clause
        clause_stmts = compile_pattern_dispatch_clause(
            param_patterns, guard_expr, body_forms, ok_var, is_generator
        )
        stmts.extend(clause_stmts)

    # If no clause matched, raise MatchError
    stmts.append(
        ast.Raise(
            exc=ast.Call(
                func=ast.Name(id="MatchError", ctx=ast.Load()),
                args=[ast.Constant(value=f"No matching clause for {fn_name}")],
                keywords=[],
            ),
            cause=None,
        )
    )

    return stmts


def compile_arity_dispatch_body(params, body_forms, has_kwargs, is_generator=False):
    """
    Compile the body of an arity case in dispatch.

    Generates parameter unpacking from __args__ and then the body.
    Now supports type annotations via ^type syntax (Phase 4).

    When a parameter has a type annotation like ^int x, this generates:
        x: int = __args__[0]
    instead of:
        x = __args__[0]
    """
    body_nodes = []

    # Unpack parameters from __args__
    items = params.items
    i = 0
    arg_index = 0

    # Track pending type annotation from ^type syntax
    pending_type_annotation = None

    while i < len(items):
        item = items[i]

        # Check for type annotation (^type before parameter)
        if isinstance(item, Decorated):
            pending_type_annotation = compile_type_annotation(item.expr)
            i += 1
            continue

        if is_symbol(item, "&"):
            # Vararg: rest = __args__[arg_index:]
            vararg_item = items[i + 1]

            # Use pending type annotation if available
            vararg_annotation = pending_type_annotation
            pending_type_annotation = None

            if isinstance(vararg_item, Symbol):
                vararg_name = normalize_name(vararg_item.name)
                value_expr = ast.Subscript(
                    value=ast.Name(id="__args__", ctx=ast.Load()),
                    slice=ast.Slice(
                        lower=ast.Constant(value=arg_index),
                        upper=None,
                        step=None,
                    ),
                    ctx=ast.Load(),
                )
                if vararg_annotation is not None:
                    # Emit annotated assignment: rest: Type = __args__[idx:]
                    body_nodes.append(
                        ast.AnnAssign(
                            target=ast.Name(id=vararg_name, ctx=ast.Store()),
                            annotation=vararg_annotation,
                            value=value_expr,
                            simple=1,
                        )
                    )
                else:
                    body_nodes.append(
                        ast.Assign(
                            targets=[ast.Name(id=vararg_name, ctx=ast.Store())],
                            value=value_expr,
                        )
                    )
            else:
                # Destructuring vararg
                temp = gensym("__vararg_")
                body_nodes.append(
                    ast.Assign(
                        targets=[ast.Name(id=temp, ctx=ast.Store())],
                        value=ast.Subscript(
                            value=ast.Name(id="__args__", ctx=ast.Load()),
                            slice=ast.Slice(
                                lower=ast.Constant(value=arg_index),
                                upper=None,
                                step=None,
                            ),
                            ctx=ast.Load(),
                        ),
                    )
                )
                body_nodes.extend(
                    compile_destructure(vararg_item, ast.Name(id=temp, ctx=ast.Load()))
                )
            i += 2

        elif is_symbol(item, "**"):
            # Kwargs: kwargs = spork_kwargs_map(__kwargs__)
            # Convert Python dict to Spork Map with Keyword keys
            kwargs_item = items[i + 1]

            # Use pending type annotation if available
            kwargs_annotation = pending_type_annotation
            pending_type_annotation = None

            # Wrap __kwargs__ with spork_kwargs_map to convert to Spork Map
            converted_kwargs = ast.Call(
                func=ast.Name(id="spork_kwargs_map", ctx=ast.Load()),
                args=[ast.Name(id="__kwargs__", ctx=ast.Load())],
                keywords=[],
            )

            if isinstance(kwargs_item, Symbol):
                kwargs_name = normalize_name(kwargs_item.name)
                if kwargs_annotation is not None:
                    body_nodes.append(
                        ast.AnnAssign(
                            target=ast.Name(id=kwargs_name, ctx=ast.Store()),
                            annotation=kwargs_annotation,
                            value=converted_kwargs,
                            simple=1,
                        )
                    )
                else:
                    body_nodes.append(
                        ast.Assign(
                            targets=[ast.Name(id=kwargs_name, ctx=ast.Store())],
                            value=converted_kwargs,
                        )
                    )
            else:
                # Destructuring kwargs
                temp = gensym("__kwargs_")
                body_nodes.append(
                    ast.Assign(
                        targets=[ast.Name(id=temp, ctx=ast.Store())],
                        value=converted_kwargs,
                    )
                )
                body_nodes.extend(
                    compile_destructure(kwargs_item, ast.Name(id=temp, ctx=ast.Load()))
                )
            i += 2

        elif is_symbol(item, "*"):
            # Keyword-only marker - skip (handled by kwargs in multi-arity)
            i += 1

        else:
            # Regular positional arg
            param_item = item

            if isinstance(item, list) and len(item) == 2:
                param_item = item[0]

            # Use pending type annotation if available
            param_annotation = pending_type_annotation
            pending_type_annotation = None

            if isinstance(param_item, Symbol):
                param_name = normalize_name(param_item.name)
                value_expr = ast.Subscript(
                    value=ast.Name(id="__args__", ctx=ast.Load()),
                    slice=ast.Constant(value=arg_index),
                    ctx=ast.Load(),
                )
                if param_annotation is not None:
                    # Emit annotated assignment: x: int = __args__[0]
                    body_nodes.append(
                        ast.AnnAssign(
                            target=ast.Name(id=param_name, ctx=ast.Store()),
                            annotation=param_annotation,
                            value=value_expr,
                            simple=1,
                        )
                    )
                else:
                    body_nodes.append(
                        ast.Assign(
                            targets=[ast.Name(id=param_name, ctx=ast.Store())],
                            value=value_expr,
                        )
                    )
            elif is_destructuring_pattern(param_item):
                # Destructuring pattern
                temp = gensym("__param_")
                body_nodes.append(
                    ast.Assign(
                        targets=[ast.Name(id=temp, ctx=ast.Store())],
                        value=ast.Subscript(
                            value=ast.Name(id="__args__", ctx=ast.Load()),
                            slice=ast.Constant(value=arg_index),
                            ctx=ast.Load(),
                        ),
                    )
                )
                body_nodes.extend(
                    compile_destructure(param_item, ast.Name(id=temp, ctx=ast.Load()))
                )
            else:
                raise SyntaxError(f"Invalid parameter: {param_item}")

            arg_index += 1
            i += 1

    # Compile the body
    for f in body_forms[:-1]:
        stmts = compile_stmt(f)
        body_nodes.extend(flatten_stmts([stmts]))

    last_form = body_forms[-1]
    if isinstance(last_form, list) and last_form and is_symbol(last_form[0]):
        head_name = last_form[0].name

        if head_name == "let":
            let_stmts = compile_let_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([let_stmts]))
        elif head_name == "do":
            do_stmts = compile_do_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([do_stmts]))
        elif head_name == "try":
            try_stmts = compile_try_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([try_stmts]))
        elif head_name == "with":
            with_stmt = compile_with_stmt_with_return(last_form[1:])
            body_nodes.append(with_stmt)
        elif head_name in ("while", "set!"):
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
            # Only add return None if not a generator
            if not is_generator:
                body_nodes.append(ast.Return(value=ast.Constant(value=None)))
        elif head_name == "return":
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
        else:
            # Regular expression - check if generator
            if is_generator:
                # Generator function - just add the statement, no return
                stmts = compile_stmt(last_form)
                body_nodes.extend(flatten_stmts([stmts]))
            else:
                # Regular function - add return
                body_nodes.append(ast.Return(value=compile_expr(last_form)))
    else:
        # Simple value - check if generator
        if is_generator:
            # Generator function - compile as statement, no return
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
        else:
            # Regular function - return it
            body_nodes.append(ast.Return(value=compile_expr(last_form)))

    return body_nodes


def compile_defn(args, form_loc=None):
    if len(args) < 2:
        raise SyntaxError("defn requires name and params")

    # Collect decorators, flags, and return type from metadata before the name
    # Uses extract_decorators_and_type to properly classify:
    # - ^async, ^generator -> flags
    # - ^int, ^(List int) -> return type annotation
    # - ^(route "/api") -> decorator
    decorated_list = []
    i = 0
    while i < len(args) and isinstance(args[i], Decorated):
        decorated_list.append(args[i])
        i += 1
    args = args[i:]

    decorators, is_async, is_generator, return_type = extract_decorators_and_type(
        decorated_list
    )

    # Compile return type annotation if present
    return_type_node = None
    if return_type is not None:
        return_type_node = compile_type_annotation(return_type)

    if len(args) < 2:
        raise SyntaxError("defn requires name and params")

    name_sym = args[0]
    if not isinstance(name_sym, Symbol):
        raise SyntaxError("defn name must be symbol")

    # Check for multi-arity syntax
    if is_multi_arity(args[1:]):
        return compile_multi_arity_defn(
            name_sym,
            args[1:],
            decorators,
            form_loc,
            is_async,
            is_generator,
            return_type_node,
        )

    params = args[1]
    if not isinstance(params, VectorLiteral):
        raise SyntaxError("defn params must be vector")
    body_forms = args[2:] or [None]
    args_node, destructure_stmts = compile_params(params.items)
    body_nodes = []

    # Check for docstring (first form is a string literal)
    docstring_node = None
    if body_forms and isinstance(body_forms[0], str):
        # Extract docstring as an Expr node
        docstring_node = ast.Expr(value=ast.Constant(value=body_forms[0]))
        # If docstring is the only form, we need at least one form for the body
        if len(body_forms) == 1:
            body_forms = [None]
        else:
            body_forms = body_forms[1:]

    # Add destructuring statements at the start of the function body
    body_nodes.extend(destructure_stmts)

    # Compile all but the last form as statements
    for f in body_forms[:-1]:
        stmts = compile_stmt(f)
        body_nodes.extend(flatten_stmts([stmts]))

    # Last form: try to return it as an expression, but handle let/do specially
    last_form = body_forms[-1]

    # Check if it's a let or do that might contain statements
    if isinstance(last_form, list) and last_form and is_symbol(last_form[0]):
        head_name = last_form[0].name

        if head_name == "let":
            # Compile let as statements, with last body form returned
            let_stmts = compile_let_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([let_stmts]))
        elif head_name == "do":
            # Compile do as statements, with last form returned
            do_stmts = compile_do_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([do_stmts]))
        elif head_name == "try":
            # Compile try as statements, with last body form returned
            try_stmts = compile_try_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([try_stmts]))
        elif head_name == "with":
            # Compile with as statements, with last body form returned
            with_stmt = compile_with_stmt_with_return(last_form[1:])
            body_nodes.append(with_stmt)
        elif head_name == "loop":
            # Compile loop as statements, with last body form returned
            loop_stmts = compile_loop_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([loop_stmts]))
        elif head_name in ("while", "set!"):
            # Pure statement forms - no return value
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
            # Only add return None if not a generator
            if not is_generator:
                ret_node = ast.Return(value=ast.Constant(value=None))
                last_loc = get_source_location(last_form)
                set_location(ret_node, last_loc)
                body_nodes.append(ret_node)
        elif head_name == "return":
            # Already a return statement
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
        else:
            # Regular expression - check if generator
            if is_generator:
                # Generator function - just add the statement, no return
                stmts = compile_stmt(last_form)
                body_nodes.extend(flatten_stmts([stmts]))
            else:
                # Regular function - add return
                ret_node = ast.Return(value=compile_expr(last_form))
                last_loc = get_source_location(last_form)
                set_location(ret_node, last_loc)
                body_nodes.append(ret_node)
    else:
        # Simple value - check if generator
        if is_generator:
            # Generator function - compile as statement, no return
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
        else:
            # Regular function - return it
            ret_node = ast.Return(value=compile_expr(last_form))
            last_loc = get_source_location(last_form)
            set_location(ret_node, last_loc)
            body_nodes.append(ret_node)

    # Ensure function has at least one statement
    if not body_nodes:
        body_nodes.append(ast.Pass())

    # Check for yield without ^generator annotation
    if contains_yield(body_nodes) and not is_generator:
        fn_name = normalize_name(name_sym.name)
        raise SyntaxError(
            f"Function '{fn_name}' contains yield but is not marked with ^generator. "
            f"Use (defn ^generator {name_sym.name} ...) for generator functions."
        )

    # Compile decorator expressions
    decorator_list = []
    for dec in decorators:
        if isinstance(dec, Symbol):
            # Simple decorator: ^staticmethod -> @staticmethod
            decorator_list.append(ast.Name(id=normalize_name(dec.name), ctx=ast.Load()))
        elif isinstance(dec, list) and dec:
            # Decorator with args: ^(route "/api") -> @route("/api")
            decorator_list.append(compile_expr(dec))
        else:
            raise SyntaxError(f"Invalid decorator expression: {dec!r}")

    if is_async:
        func = ast.AsyncFunctionDef(
            name=normalize_name(name_sym.name),
            args=args_node,
            body=body_nodes,
            decorator_list=decorator_list,
            returns=return_type_node,
        )
    else:
        func = ast.FunctionDef(
            name=normalize_name(name_sym.name),
            args=args_node,
            body=body_nodes,
            decorator_list=decorator_list,
            returns=return_type_node,
        )

    # Set source location on the function definition
    if form_loc:
        set_location(func, form_loc)
    else:
        copy_location(func, name_sym)

    # Inject any nested function definitions at the start of the function body
    # but AFTER the docstring if present
    nested_funcs = get_compile_context().get_and_clear_functions()
    if docstring_node:
        # Docstring must be first, then nested functions, then rest of body
        func.body = [docstring_node] + nested_funcs + func.body
    elif nested_funcs:
        func.body = nested_funcs + func.body

    return func


def compile_params(items):
    """
    Compile function parameters with support for defaults, keyword-only args,
    kwargs, and type annotations.

    Syntax:
    - [x (y 1)]       -> def f(x, y=1):
    - [x & rest]      -> def f(x, *rest):
    - [x # y]         -> def f(x, *, y):
    - [x # (y 1)]     -> def f(x, *, y=1):
    - [x ** k]        -> def f(x, **k):
    - [x & rest ** k] -> def f(x, *rest, **k):
    - [x # y ** k]    -> def f(x, *, y, **k):

    Type annotations (Phase 3):
    - [^int x]        -> def f(x: int):
    - [^int x ^str y] -> def f(x: int, y: str):
    - [^(List int) items] -> def f(items: List[int]):

    Returns: (ast.arguments, List[ast.stmt])
    """
    # Lists for ast.arguments
    pos_args: list[ast.arg] = []
    pos_defaults: list[ast.expr] = []

    vararg: Optional[ast.arg] = None

    kwonly_args: list[ast.arg] = []
    kw_defaults: list[Optional[ast.expr]] = []

    kwarg: Optional[ast.arg] = None

    # Side effects (destructuring assignments)
    destructure_stmts: list[ast.stmt] = []

    # State machine: "pos", "rest", "kw", "kwargs"
    state = "pos"

    # Track pending type annotation from ^type syntax
    pending_type_annotation = None

    i = 0
    while i < len(items):
        item = items[i]

        # 0. Check for type annotation (^type before parameter)
        if isinstance(item, Decorated):
            # This is a type annotation like ^int or ^(List int)
            pending_type_annotation = compile_type_annotation(item.expr)
            i += 1
            continue

        # 1. Handle Markers

        # Check for Kwargs (**)
        if is_symbol(item, "**"):
            if state == "kwargs":
                raise SyntaxError("** can only appear once")
            state = "kwargs"

            # The next item must be the kwarg name
            if i + 1 >= len(items):
                raise SyntaxError("** must be followed by a name")

            kwarg_item = items[i + 1]
            i += 2  # Skip ** and name

            # Use pending type annotation if available
            kwarg_annotation = pending_type_annotation
            pending_type_annotation = None

            if isinstance(kwarg_item, Symbol):
                kwarg_name = normalize_name(kwarg_item.name)
                kwarg = ast.arg(arg=kwarg_name, annotation=kwarg_annotation)
                # Convert Python kwargs dict to Spork Map with Keyword keys
                # kwarg_name = spork_kwargs_map(kwarg_name)
                destructure_stmts.insert(
                    0,
                    ast.Assign(
                        targets=[ast.Name(id=kwarg_name, ctx=ast.Store())],
                        value=ast.Call(
                            func=ast.Name(id="spork_kwargs_map", ctx=ast.Load()),
                            args=[ast.Name(id=kwarg_name, ctx=ast.Load())],
                            keywords=[],
                        ),
                    ),
                )
            else:
                # Destructuring pattern for kwargs
                temp = gensym("__kwarg_")
                kwarg = ast.arg(arg=temp, annotation=None)
                # Convert before destructuring
                convert_stmt = ast.Assign(
                    targets=[ast.Name(id=temp, ctx=ast.Store())],
                    value=ast.Call(
                        func=ast.Name(id="spork_kwargs_map", ctx=ast.Load()),
                        args=[ast.Name(id=temp, ctx=ast.Load())],
                        keywords=[],
                    ),
                )
                destructure_stmts.insert(0, convert_stmt)
                temp_load = ast.Name(id=temp, ctx=ast.Load())
                destructure_stmts.extend(compile_destructure(kwarg_item, temp_load))
            continue

        # Check for Varargs (&)
        if is_symbol(item, "&"):
            if state not in ("pos",):
                raise SyntaxError(
                    "& (rest) must come before * (keyword args) and ** (kwargs)"
                )
            state = "rest"

            # The next item must be the vararg name
            if i + 1 >= len(items):
                raise SyntaxError("& must be followed by a name")

            vararg_item = items[i + 1]
            i += 2  # Skip & and name

            # Use pending type annotation if available
            vararg_annotation = pending_type_annotation
            pending_type_annotation = None

            # Handle destructuring in vararg: (defn f [& [x y]])
            if isinstance(vararg_item, Symbol):
                vararg = ast.arg(
                    arg=normalize_name(vararg_item.name), annotation=vararg_annotation
                )
            else:
                # E.g. (defn f [& [first & rest]])
                temp = gensym("__vararg_")
                vararg = ast.arg(arg=temp, annotation=None)
                temp_load = ast.Name(id=temp, ctx=ast.Load())
                destructure_stmts.extend(compile_destructure(vararg_item, temp_load))
            continue

        # Check for Keyword Marker (*)
        if is_symbol(item, "*"):
            if state == "kwargs":
                raise SyntaxError("* (keyword args) must come before ** (kwargs)")
            state = "kw"
            i += 1
            continue

        # 2. Extract Name and Default Value
        # Format can be `name` or `(name default_value)`
        param_item = item
        default_val_expr = None
        has_default = False

        # In Spork reader, (x 1) is a list. [x 1] is a Vector.
        # We use list () for defaults to distinguish from destructuring []
        if isinstance(item, list):
            if len(item) != 2:
                raise SyntaxError(f"Parameter default must be (name value), got {item}")
            param_item = item[0]
            default_val_expr = compile_expr(item[1])
            has_default = True

        # 3. Handle Destructuring vs Simple Symbol
        py_arg = None

        # Use pending type annotation if available
        param_annotation = pending_type_annotation
        pending_type_annotation = None

        if isinstance(param_item, Symbol):
            py_arg = ast.arg(
                arg=normalize_name(param_item.name), annotation=param_annotation
            )
        elif is_destructuring_pattern(param_item):
            # Generate temp param name for Python signature
            temp = gensym("__param_")
            py_arg = ast.arg(arg=temp, annotation=param_annotation)

            # Create destructuring logic for body
            temp_load = ast.Name(id=temp, ctx=ast.Load())
            destructure_stmts.extend(compile_destructure(param_item, temp_load))
        else:
            raise SyntaxError(f"Invalid parameter format: {param_item}")

        # 4. Add to AST based on state
        if state == "pos":
            pos_args.append(py_arg)
            if has_default and default_val_expr is not None:
                pos_defaults.append(default_val_expr)
            elif pos_defaults:
                # In Python positional args, you can't have a non-default after a default
                raise SyntaxError("Non-default argument follows default argument")

        elif state == "rest":
            raise SyntaxError("Only one variable allowed after &")

        elif state == "kw":
            kwonly_args.append(py_arg)
            # In Python, kwonly args can be required (default=None) or optional
            kw_defaults.append(default_val_expr)

        elif state == "kwargs":
            raise SyntaxError("No parameters allowed after ** kwargs")

        i += 1

    args_node = ast.arguments(
        posonlyargs=[],
        args=pos_args,
        vararg=vararg,
        kwonlyargs=kwonly_args,
        kw_defaults=kw_defaults,
        kwarg=kwarg,
        defaults=pos_defaults,
    )

    return args_node, destructure_stmts


def compile_multi_arity_fn_expr(arity_forms, is_async=False, is_generator=False):
    """
    Compile a multi-arity anonymous function.

    Example:
        (fn
          ([x] x)
          ([x y] (+ x y)))

    Supports async:
        (fn ^async
          ([x] (await x))
          ([x y] (await (some-async x y))))

    Supports generator:
        (fn ^generator
          ([x] (yield x))
          ([x y] (yield x) (yield y)))
    """
    fn_name = gen_fn_name()

    # Parse all arities
    arities = []
    has_variadic = False
    has_any_kwargs = False

    for arity_form in arity_forms:
        params, body_forms, min_args, has_vararg, has_kwargs = parse_arity(arity_form)
        if has_vararg:
            if has_variadic:
                raise SyntaxError("Only one variadic arity allowed per function")
            has_variadic = True
        if has_kwargs:
            has_any_kwargs = True
        arities.append((params, body_forms, min_args, has_vararg, has_kwargs))

    # Sort arities: fixed arities first (by min_args), variadic last
    fixed_arities = [(p, b, m, v, k) for p, b, m, v, k in arities if not v]
    variadic_arities = [(p, b, m, v, k) for p, b, m, v, k in arities if v]

    # Check for duplicate fixed arities
    fixed_counts = [m for _, _, m, _, _ in fixed_arities]
    if len(fixed_counts) != len(set(fixed_counts)):
        raise SyntaxError("Duplicate arity definitions")

    # Sort fixed arities by arg count
    fixed_arities.sort(key=lambda x: x[2])

    # Build the dispatch function
    args_node = ast.arguments(
        posonlyargs=[],
        args=[],
        vararg=ast.arg(arg="__args__", annotation=None),
        kwonlyargs=[],
        kw_defaults=[],
        kwarg=ast.arg(arg="__kwargs__", annotation=None) if has_any_kwargs else None,
        defaults=[],
    )

    body_nodes = []

    # __n__ = len(__args__)
    body_nodes.append(
        ast.Assign(
            targets=[ast.Name(id="__n__", ctx=ast.Store())],
            value=ast.Call(
                func=ast.Name(id="len", ctx=ast.Load()),
                args=[ast.Name(id="__args__", ctx=ast.Load())],
                keywords=[],
            ),
        )
    )

    # Track nested functions created while compiling this fn's body
    before_count = len(get_compile_context().nested_functions)

    # Build if/elif chain for dispatch
    dispatch_cases = []

    for params, body_forms, min_args, _, has_kwargs in fixed_arities:
        test = ast.Compare(
            left=ast.Name(id="__n__", ctx=ast.Load()),
            ops=[ast.Eq()],
            comparators=[ast.Constant(value=min_args)],
        )
        arity_body = compile_arity_dispatch_body(
            params, body_forms, has_kwargs, is_generator
        )
        dispatch_cases.append((test, arity_body))

    if variadic_arities:
        params, body_forms, min_args, has_vararg, has_kwargs = variadic_arities[0]
        test = ast.Compare(
            left=ast.Name(id="__n__", ctx=ast.Load()),
            ops=[ast.GtE()],
            comparators=[ast.Constant(value=min_args)],
        )
        arity_body = compile_arity_dispatch_body(
            params, body_forms, has_kwargs, is_generator
        )
        dispatch_cases.append((test, arity_body))

    if dispatch_cases:
        error_msg = "fn called with wrong number of arguments"
        else_body = [
            ast.Raise(
                exc=ast.Call(
                    func=ast.Name(id="TypeError", ctx=ast.Load()),
                    args=[ast.Constant(value=error_msg)],
                    keywords=[],
                ),
                cause=None,
            )
        ]

        current_else: list[ast.stmt] = list(else_body)
        for test, arity_body in reversed(dispatch_cases):
            current_if = ast.If(
                test=test,
                body=arity_body,
                orelse=current_else,
            )
            current_else = [current_if]

        body_nodes.append(current_else[0])

    # Check for yield without ^generator annotation
    if contains_yield(body_nodes) and not is_generator:
        raise SyntaxError(
            "Anonymous function contains yield but is not marked with ^generator. "
            "Use (fn ^generator [...] ...) for generator functions."
        )

    # Inject only the nested functions created while compiling this fn's body
    ctx = get_compile_context()
    after_count = len(ctx.nested_functions)
    if after_count > before_count:
        # Extract only the functions created during this fn's compilation
        nested_funcs = ctx.nested_functions[before_count:after_count]
        body_nodes = nested_funcs + body_nodes
        # Remove these functions from the context since we've injected them
        ctx.nested_functions = (
            ctx.nested_functions[:before_count] + ctx.nested_functions[after_count:]
        )

    if is_async:
        func_def = ast.AsyncFunctionDef(
            name=fn_name,
            args=args_node,
            body=cast(list[ast.stmt], body_nodes),
            decorator_list=[],
        )
    else:
        func_def = ast.FunctionDef(
            name=fn_name,
            args=args_node,
            body=cast(list[ast.stmt], body_nodes),
            decorator_list=[],
        )

    # Add the function definition to the context to be injected into the enclosing scope
    get_compile_context().add_function(func_def)
    return ast.Name(id=fn_name, ctx=ast.Load())


def compile_fn_expr(args, ctx=None):
    """
    Compile (fn [x y] body...) to a nested function definition.
    This allows statements like set!, for, while, etc. in the function body.
    Supports varargs with & syntax: (fn [x & rest] ...)
    Supports multi-arity: (fn ([x] x) ([x y] (+ x y)))
    Supports async: (fn ^async [x] (await x))
    Supports generator: (fn ^generator [x] (yield x))

    The function is defined in the enclosing scope, which naturally captures
    variables from that scope (closures work like Python's nested functions).
    """
    if len(args) < 1:
        raise SyntaxError("fn requires parameter vector")

    # Check for ^async and ^generator decorators
    is_async = False
    is_generator = False
    i = 0
    while i < len(args) and isinstance(args[i], Decorated):
        dec_expr = args[i].expr
        if isinstance(dec_expr, Symbol) and dec_expr.name == "async":
            is_async = True
        elif isinstance(dec_expr, Symbol) and dec_expr.name == "generator":
            is_generator = True
        i += 1
    args = args[i:]

    if len(args) < 1:
        raise SyntaxError("fn requires parameter vector")

    # Check for multi-arity syntax
    if is_multi_arity(args):
        return compile_multi_arity_fn_expr(args, is_async, is_generator)

    params = args[0]
    if not isinstance(params, VectorLiteral):
        raise SyntaxError("fn parameters must be a vector")

    body_forms = args[1:] or [None]

    # Generate a unique name for this anonymous function
    fn_name = gen_fn_name()

    # Compile parameters (same as defn)
    args_node, destructure_stmts = compile_params(params.items)

    # Compile body (same as defn)
    body_nodes = []

    # Add destructuring statements at the start of the function body
    body_nodes.extend(destructure_stmts)

    # Track nested functions created while compiling this fn's body
    before_count = len(get_compile_context().nested_functions)

    # Compile all but the last form as statements
    for f in body_forms[:-1]:
        stmts = compile_stmt(f)
        body_nodes.extend(flatten_stmts([stmts]))

    # Last form: try to return it as an expression, but handle let/do specially
    last_form = body_forms[-1]

    # Check if it's a let or do that might contain statements
    if isinstance(last_form, list) and last_form and is_symbol(last_form[0]):
        head_name = last_form[0].name

        if head_name == "let":
            let_stmts = compile_let_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([let_stmts]))
        elif head_name == "do":
            do_stmts = compile_do_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([do_stmts]))
        elif head_name == "try":
            try_stmts = compile_try_stmt_with_return(last_form[1:])
            body_nodes.extend(flatten_stmts([try_stmts]))
        elif head_name == "with":
            with_stmt = compile_with_stmt_with_return(last_form[1:])
            body_nodes.append(with_stmt)
        elif head_name in ("while", "set!"):
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
            # Only add return None if not a generator
            if not is_generator:
                body_nodes.append(ast.Return(value=ast.Constant(value=None)))
        elif head_name == "return":
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
        else:
            # Regular expression - check if generator
            if is_generator:
                # Generator function - just add the statement, no return
                stmts = compile_stmt(last_form)
                body_nodes.extend(flatten_stmts([stmts]))
            else:
                # Regular function - add return
                body_nodes.append(ast.Return(value=compile_expr(last_form)))
    else:
        # Simple value - check if generator
        if is_generator:
            # Generator function - compile as statement, no return
            stmts = compile_stmt(last_form)
            body_nodes.extend(flatten_stmts([stmts]))
        else:
            # Regular function - return it
            body_nodes.append(ast.Return(value=compile_expr(last_form)))

    if not body_nodes:
        body_nodes.append(ast.Pass())

    # Check for yield without ^generator annotation
    if contains_yield(body_nodes) and not is_generator:
        raise SyntaxError(
            "Anonymous function contains yield but is not marked with ^generator. "
            "Use (fn ^generator [...] ...) for generator functions."
        )

    # Inject only the nested functions created while compiling this fn's body
    ctx = get_compile_context()
    after_count = len(ctx.nested_functions)
    if after_count > before_count:
        # Extract only the functions created during this fn's compilation
        nested_funcs = ctx.nested_functions[before_count:after_count]
        body_nodes = nested_funcs + body_nodes
        # Remove these functions from the context since we've injected them
        ctx.nested_functions = (
            ctx.nested_functions[:before_count] + ctx.nested_functions[after_count:]
        )

    if is_async:
        func_def = ast.AsyncFunctionDef(
            name=fn_name,
            args=args_node,
            body=body_nodes,  # type: ignore
            decorator_list=[],
        )
    else:
        func_def = ast.FunctionDef(
            name=fn_name,
            args=args_node,
            body=body_nodes,  # type: ignore
            decorator_list=[],
        )

    # Add the function definition to the context to be injected into the enclosing scope
    get_compile_context().add_function(func_def)

    # Return a reference to the function name
    return ast.Name(id=fn_name, ctx=ast.Load())
